### ISSUE TITLE
connecting to mac address

### ISSUE THREAD

**Issue by joelwass** [joshblour/discovery-react#2]
Is there any documentation on connection to a specific mac address via react-discovery?

Sorry if I missed something when poking around. Thanks

**Comment by yonahforst** [comment]
@joelwass you're not actually connecting to the other devices. You're just observing them, kind of just to see who's around.

**Comment by joelwass** [comment]
Ok, is react support for ble connection still young?

**Comment by yonahforst** [comment]
Not sure but it's out of the scope of this library... :)
