### ISSUE TITLE
ReactNativeDiscovery.setShouldDiscover was called with 2 arguments, but expects 1.

### ISSUE THREAD

**Issue by patrickhoehn** [joshblour/discovery-react#4]
I used your example in a simple test app and got this error: 

`[error][tid:main][RCTModuleMethod.m:470] ReactNativeDiscovery.setShouldDiscover was called with 2 arguments, but expects 1. If you haven't changed this method yourself, this usually means that your versions of the native code and JavaScript code are out of sync. Updating both should make this error go away.`

If I use `(true)` instead of `(myUUID, true)`, no errors appear but the app does not work. I installed the app via testflight on a iOS device and tried to find another device which is connected to Xcode for logging, but the console remains empty.

**Comment by patrickhoehn** [comment]
I changed `(myUUID, true)` back to `(true)` to make the error disappear. Discovery is still not working, but **the app is definitely advertising** with the correct user name and UUID, as long as it is not running in the background. I checked that with the example app from react-native-ble-plx.

**Comment by yonahforst** [comment]
@patrickhoehn - so sorry for the late reply to this. somehow i missed it. Are you still having this issue?

**Comment by yonahforst** [comment]
closing for now, if this is still an issue, please reopen
